const questions = ["When is the loneliest you have ever felt?",
    "What has been your biggest challenge so far?",
    "What was the last time you cried?",
    "What is your most important work in progress currently?",
    "Are you holding on to something that you need to let go of?",
    "What is something you want to get off your chest?",
    "What qualities of your character do you prefer to remain hidden from others?",
    "What qualities of your character are you particularly proud of?",
    "What in life gets you really excited?",
    "What could you do to bring more of what excites you into your life?",
    "Summarized in just a few sentences, what is your life's story?",
    "What do you want the next chapter in your life to be?",
    "What would you say is the greatest accomplishment of your life so far?",
    "What do you want to make sure you do, achieve, or experience before you're gone?",
    "In recent years, what's the biggest lesson you've learned about yourself?",
    "Who inspires you most, and why do you find them inspiring?",
    "What was the biggest turning point in your life, and how did that experience change you?",
    "What are you taking for granted that you want to remember to be grateful for?",
    "Think for a moment about the biggest problem right now in your life. If that problem was happening to a close friend instead of you, what would you say to comfort or advise that friend?",
    "What meaningful or important thing should you tell a particular person that you haven't said to them yet?",
    "What's one of the best days you've had in your entire life? Describe what happened that day.",
    "What in your life that you have the power to change is most limiting your long-term happiness?",
    "What could you start doing now to address what is most limiting your happiness?",
    "What is the most important thing you know you should do but have trouble getting yourself to do?",
    "In your opinion, what is the purpose or meaning of life?",
    "How is the best version of yourself different from how you sometimes behave?",
    "What has kept you hopeful in life's most challenging moments?",
    "During what period of your life were you the happiest, and why were you so happy then?",
    "If you knew for a fact that you were going to die exactly ten years from now, how would you change your current behavior?",
    "Suppose you knew that you would die instantly (but painlessly) in seven days. What would you spend your last week doing?",
    "What would you spend that day doing if you could plan one nearly perfect (but still realistic) day for yourself? Describe that day, from when you wake up until you go to sleep.",
    "Do you often hold back your feelings?",
    "What would you wish people around you would do more often?",
    "Do you sometimes feel disconnected from others? What helps you in such moments?",
    "What is your relationship with your parents? How does it affect your relationship with others?",
    "What are the most important things in your life?",
    "What makes you look down on other people?",
    "What is your biggest insecurity?",
    "What do you think makes other people look down on you?",
    "What is the personal quality of which you’re most ashamed?",
    "With whom do you have the best connection in your family? Why?",
    "Would you want to be a parent? Why? How would you want to raise a kid?",
    "What emotion do you feel most often?",
    "How do you hope you’ll change as a person in the future?",
    "What do you value most in friendship?",
    "What is love?",
    "How do you assign self-worth?",
    "Are there any mind-boggling observations you wish you could share with others but there has never been room for it?",
    "How would you describe yourself in a couple of sentences?",
    "What does your nationality mean to you?",
    "How confident do you feel about opening up to these people while playing this game?",
    "What would you want to change about your body?",
    "What feeling drives you?",
    "What was the worst thing that has ever happened to you?",
    "What masculine and feminine qualities do you identify with?",
    "Have you ever experienced true love?",
    "Do you sometimes talk to yourself?",
    "Do you believe in destiny?",
    "Why haven't you done that thing you're supposed to do?",
    "What do you feel bad about liking/wanting to do?",
    "What about yourself freaks you out?",
    "How do you differ in talking with yourself compared to talking with others?",
    "If you were reborn as an animal, which would you like to be?",
    "Imagine your ten-year-younger self talking to your current self. Would you get along well and what advice would your younger self give you?",
    "Would you choose to live forever if you had the chance?",
    "You can choose between three superpowers: \n a. Invisibility \t b. Teleportation \t c. Absolute memory \n Why did you choose this superpower and how would you use it?",
    "Was there a situation during the day/week when you didn't do what you wanted to do? What was that and would you do differently now?",
    "When you make decisions, do you like to listen to others or rather to yourself? Would you like to change that?",
    "If you had to choose four theme songs for your childhood, adolescence, adulthood and in your old age, what would they be?",
    "Are there dreams that you dream over and over again? Would you like to talk about them?",
    "If you could choose any place in the world to be immediately at any time, what place would it be?",
    "What do you prefer? Sweet or salty?",
    "Which fear would you like to overcome in the future?",
    "Imagine you are a cucumber, and someone is about to peel you. With what arguments would you try to stop the person?",
    "If you could only be either rational or emotional, which would you choose?",
    "If you could give a 15min speech to the whole world, what would it be about?",
    "What do you want others to think of you when you are not there anymore? Do you care about it anyway?",
    "Are you happy with what your are doing?",
    "Do you think it is possible to live without having an impact on the world? What impact would you like to have on the world?",
    "Could you imagine a world where possessing power is not what people admire?",
    "What is your most controversial opinion?",
    "What’s more important: time or money?",
    "What’s more important: friends or family?",
    "What was the biggest learning you ever got from a relationship?",
    "What do you love about yourself?",
    "What grounds you when you feel stressed or anxious?",
    "Imagine your dream life - what is it like?",
    "Where do you live, what are you doing, who are you with?",
    "What is the most terrifying dream you have ever had?",
    "What is the funniest thing you ever whitnessed that still brings you joy thinking about it now?",
    "When do you feel most like yourself?"
]

export default questions